nginx:
  image: nginx
  ports:
    - 80:80
  links:
    - registry
  volumes:
    - ./conf.d/:/etc/nginx/conf.d:ro
    - ./logs/:/etc/nginx/logs:rw

registry:
  image: registry:2.4.1
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  volumes:
    - /opt/registry:/data