nginx:
    build: ./nginx
    ports:
      - "8002:80"
    links:
      - php
    volumes:
      - /www/now:/opt/now:rw
      - ./:/opt/sites
      # - ./logs/nginx/:/etc/nginx/logs:rw

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - mysql
      - redis
    volumes:
      - /www/now:/opt:rw
      - ./logs/php-fpm/:/usr/local/etc/logs

mysql:
    build: ./mysql 
    ports:
      - "3306:3306"
    # volumes:
    #   - /www/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASS: 123456

redis:
    build: ./redis
    ports:
      - "6379:6379"