download:
	wget https://pecl.php.net/get/redis-2.2.7.tgz -O php/redis.tgz
	wget https://pecl.php.net/get/xdebug-2.4.0.tgz -O php/xdebug.tgz
	wget https://pecl.php.net/get/xhprof-0.9.4.tgz -O php/xhprof.tgz
	wget https://getcomposer.org/composer.phar -O php/composer.phar
	wget https://pecl.php.net/get/swoole-1.8.9.tgz -O php/swoole-1.8.9.tgz
	wget https://pecl.php.net/get/memcached-2.2.0.tgz -O php/memcached.tgz
	wget https://pecl.php.net/get/oci8-2.1.1.tgz -O php/oci8-2.1.1.tgz
	wget https://pecl.php.net/get/oci8-2.0.11.tgz -O php/oci8-2.0.11.tgz
	wget https://pecl.php.net/get/mongodb-1.1.9.tgz -O php/mongodb-1.1.9.tgz
	wget https://pecl.php.net/get/yaf-3.0.4.tgz -O php/yaf-3.0.4.tgz
	wget https://pecl.php.net/get/mongo-1.6.14.tgz -O php/mongo-1.6.14.tgz
	
	