tomcat:
  image: registry.domain.com/dev/tomcat:8.0
  container_name: tomcat
  ports:
    - "18080:8080"
  volumes:
    - ./docker1.war:/usr/local/tomcat/ROOT.war
  command:
    ["/usr/local/tomcat/deployWar.sh"]
# db:
#   image: registry.domain.com/dev/mysql:5.6
#   container_name: mysql
#   ports:
#     - "3306:3306"
#   environment:
#     MYSQL_ROOT_PASSWORD: 123456
#     MYSQL_USER: test
#     MYSQL_PASS: 123456