FROM node:4.4

MAINTAINER taoanton@gmail.com

RUN  npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN  cnpm install -g gulp
RUN  cnpm install -g gitbook-cli
RUN  cnpm install -g bower
RUN  gitbook help

